### ISSUE TITLE
Change the word "fork it" to "clone", including icon

### ISSUE THREAD

**Issue by eriklindgren** [prototypsthlm/taco#104]
icon: document-duplicate or maybe square-2-stack

**Comment by leilabb** [comment]
<img width="604" alt="Skärmavbild 2024-01-16 kl  10 12 54" src="https://github.com/prototypsthlm/taco/assets/8995968/d917bf3a-7c06-4fc9-8d1e-03e067c75a93">

**Comment by tonioriol** [comment]
> How about the modal after clicking the "clone" icon? Can I go ahead and change the copy there as well? @tonioriol 
> 
> 
> 
> 
> 
> 
> 
> <img width="604" alt="Skärmavbild 2024-01-16 kl  10 12 54" src="https://github.com/prototypsthlm/taco/assets/8995968/d917bf3a-7c06-4fc9-8d1e-03e067c75a93">
> 
> 

Yes ofc, go ahead :)

**Comment by leilabb** [comment]
Yes true, will check that. Already made a PR though

**Comment by tonioriol** [comment]
> Yes true, will check that. Already made a PR though

Not a problem, you can add new commits to the branch, and they will land on the pr
