### ISSUE TITLE
Code block improvements

### ISSUE THREAD

**Issue by eriklindgren** [prototypsthlm/taco#106]
* Syntax highlighting/color code blocks, depending on the language.
  Investigate good components for this. Maybe:
  * https://github.com/highlightjs/highlight.js?
  * https://github.com/markedjs/marked-highlight
  * https://magidoc.js.org/svelte-plugins/marked
* Ability to copy the entire block (with a copy button in the top right corner).

**Comment by brokelyn** [comment]
Seems to be done
