### ISSUE TITLE
Clarify copy when creating a team

### ISSUE THREAD

**Issue by eriklindgren** [prototypsthlm/taco#98]
It says you can set the key later in settings, but it won't let you create the team without it.

<img width="1030" alt="Screenshot 2023-12-04 at 12 13 42" src="https://github.com/prototypsthlm/taco/assets/80689/7400164c-bc6d-4d7f-bd3b-50baf62410a4">

**Comment by tonioriol** [comment]
Yes, the key wasn't required, but that changed and now it is. So you should change the copy to say something like:

`You need an OpenAI API key to create a team. You can get one in https://platform.openai.com`

**Comment by leilabb** [comment]
Thanks!
